# runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: denbi
spec:
  replicas: 1
  # containerMode: kubernetes
  template:
    spec:
      # image: summerwind/actions-runner-dind
      # dockerdWithinRunnerContainer: true
      dockerEnabled: false
      # dockerMTU: 1442
      repository: amun-ai/hypha-k8s
      labels:
        - denbi
      # volumes:
      #   - name: docker-extra
      #     hostPath:
      #       path: /mnt/docker-extra
      #       type: DirectoryOrCreate
      #   - name: repo
      #     hostPath:
      #       path: /mnt/repo
      #       type: DirectoryOrCreate
      # dockerVolumeMounts:
      #   - mountPath: /var/lib/docker
      #     name: docker-extra
      # ephemeral: false
      # containerMode: kubernetes
      # serviceAccountName: actions-runner-controller
      # workVolumeClaimTemplate:
      #   storageClassName: "cinder-csi"
      #   accessModes:
      #   - ReadWriteOnce
      #   resources:
      #     requests:
      #       storage: 10Gi