rbac:
  create: true
# Crucial for cert-manager to work for some reason: 
defaultBackend:
  enabled: true

controller:
  # service:
    # loadBalancerIP: 192.168.1.61
  ingressClassResource:
    default: true