# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tms_python_client.proto import error_code_pb2 as proto_dot_error__code__pb2

from tms_python_client.proto.error_code_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/common.proto\x12\x11triton.management\x1a\x16proto/error-code.proto\"E\n\x07Version\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05patch\x18\x03 \x01(\x05\x12\r\n\x05label\x18\x04 \x01(\t\"l\n\rRequestHeader\x12/\n\x0b\x61pi_version\x18\x01 \x01(\x0b\x32\x1a.triton.management.Version\x12\x12\n\nuser_agent\x18\x02 \x01(\t\x12\x16\n\x0e\x61uthentication\x18\x03 \x01(\t\"\xb9\x01\n\x0eResponseHeader\x12/\n\x0b\x61pi_version\x18\x01 \x01(\x0b\x32\x1a.triton.management.Version\x12\x0e\n\x06server\x18\x02 \x01(\t\x12*\n\x04\x63ode\x18\x03 \x01(\x0e\x32\x1c.triton.management.ErrorCode\x12\x18\n\x10\x61uthenticate_uri\x18\x04 \x01(\t\x12\x10\n\x08messages\x18\x06 \x03(\t\x12\x0e\n\x06\x65rrors\x18\x07 \x03(\t\"\x1a\n\tTimestamp\x12\r\n\x05value\x18\x01 \x01(\x12\"\x1b\n\x08\x44uration\x12\x0f\n\x07seconds\x18\x01 \x01(\rBM\n\x1a\x63om.triton.management.grpcZ\x16triton.management.grpc\xaa\x02\x16Triton.Management.GrpcP\x00\x62\x06proto3')



_VERSION = DESCRIPTOR.message_types_by_name['Version']
_REQUESTHEADER = DESCRIPTOR.message_types_by_name['RequestHeader']
_RESPONSEHEADER = DESCRIPTOR.message_types_by_name['ResponseHeader']
_TIMESTAMP = DESCRIPTOR.message_types_by_name['Timestamp']
_DURATION = DESCRIPTOR.message_types_by_name['Duration']
Version = _reflection.GeneratedProtocolMessageType('Version', (_message.Message,), {
  'DESCRIPTOR' : _VERSION,
  '__module__' : 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:triton.management.Version)
  })
_sym_db.RegisterMessage(Version)

RequestHeader = _reflection.GeneratedProtocolMessageType('RequestHeader', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTHEADER,
  '__module__' : 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:triton.management.RequestHeader)
  })
_sym_db.RegisterMessage(RequestHeader)

ResponseHeader = _reflection.GeneratedProtocolMessageType('ResponseHeader', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEHEADER,
  '__module__' : 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:triton.management.ResponseHeader)
  })
_sym_db.RegisterMessage(ResponseHeader)

Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:triton.management.Timestamp)
  })
_sym_db.RegisterMessage(Timestamp)

Duration = _reflection.GeneratedProtocolMessageType('Duration', (_message.Message,), {
  'DESCRIPTOR' : _DURATION,
  '__module__' : 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:triton.management.Duration)
  })
_sym_db.RegisterMessage(Duration)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.triton.management.grpcZ\026triton.management.grpc\252\002\026Triton.Management.Grpc'
  _VERSION._serialized_start=65
  _VERSION._serialized_end=134
  _REQUESTHEADER._serialized_start=136
  _REQUESTHEADER._serialized_end=244
  _RESPONSEHEADER._serialized_start=247
  _RESPONSEHEADER._serialized_end=432
  _TIMESTAMP._serialized_start=434
  _TIMESTAMP._serialized_end=460
  _DURATION._serialized_start=462
  _DURATION._serialized_end=489
# @@protoc_insertion_point(module_scope)
