# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/error-code.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/error-code.proto\x12\x11triton.management*\xcc\x03\n\tErrorCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x15\n\x11\x45RROR_BAD_REQUEST\x10\x01\x12\x1f\n\x1b\x45RROR_AUTHORIZATION_INVALID\x10\x02\x12\x1c\n\x18\x45RROR_USER_AGENT_INVALID\x10\x03\x12\x19\n\x15\x45RROR_VERSION_INVALID\x10\x04\x12\x1d\n\x19\x45RROR_VERSION_UNSUPPORTED\x10\x05\x12\x19\n\x14\x45RROR_AUTHENTICATION\x10\xe9\x07\x12\x17\n\x12\x45RROR_UNAUTHORIZED\x10\xea\x07\x12\x17\n\x12\x45RROR_UNPRIVILEGED\x10\xeb\x07\x12 \n\x1b\x45RROR_AUTHORITY_UNAVAILABLE\x10\xd1\x0f\x12\x1e\n\x19\x45RROR_CLUSTER_UNAVAILABLE\x10\xd2\x0f\x12\x1f\n\x1a\x45RROR_DATABASE_UNAVAILABLE\x10\xd3\x0f\x12\x1e\n\x19\x45RROR_NETWORK_UNAVAILABLE\x10\xd4\x0f\x12\x1e\n\x19\x45RROR_STORAGE_UNAVAILABLE\x10\xd5\x0f\x12\x1c\n\x17\x45RROR_REQUEST_TIMED_OUT\x10\xd6\x0f\x12\x14\n\x0f\x45RROR_UNHANDLED\x10\xd7\x0f\x42M\n\x1a\x63om.triton.management.grpcZ\x16triton.management.grpc\xaa\x02\x16Triton.Management.Grpcb\x06proto3')

_ERRORCODE = DESCRIPTOR.enum_types_by_name['ErrorCode']
ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
SUCCESS = 0
ERROR_BAD_REQUEST = 1
ERROR_AUTHORIZATION_INVALID = 2
ERROR_USER_AGENT_INVALID = 3
ERROR_VERSION_INVALID = 4
ERROR_VERSION_UNSUPPORTED = 5
ERROR_AUTHENTICATION = 1001
ERROR_UNAUTHORIZED = 1002
ERROR_UNPRIVILEGED = 1003
ERROR_AUTHORITY_UNAVAILABLE = 2001
ERROR_CLUSTER_UNAVAILABLE = 2002
ERROR_DATABASE_UNAVAILABLE = 2003
ERROR_NETWORK_UNAVAILABLE = 2004
ERROR_STORAGE_UNAVAILABLE = 2005
ERROR_REQUEST_TIMED_OUT = 2006
ERROR_UNHANDLED = 2007


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.triton.management.grpcZ\026triton.management.grpc\252\002\026Triton.Management.Grpc'
  _ERRORCODE._serialized_start=46
  _ERRORCODE._serialized_end=506
# @@protoc_insertion_point(module_scope)
