# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/model-state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/model-state.proto\x12\x11triton.management*\xa8\x02\n\nModelState\x12\x17\n\x13MODEL_STATE_UNKNOWN\x10\x00\x12\x17\n\x13MODEL_STATE_PENDING\x10\x01\x12\x18\n\x14MODEL_STATE_FETCHING\x10\x02\x12\x16\n\x12MODEL_STATE_CACHED\x10\x03\x12\x17\n\x13MODEL_STATE_LOADING\x10\x04\x12\x15\n\x11MODEL_STATE_READY\x10\x05\x12\x19\n\x15MODEL_STATE_UNLOADING\x10\x06\x12\x17\n\x13MODEL_STATE_REMOVED\x10\x07\x12\x1b\n\x17MODEL_STATE_UNAVAILABLE\x10\x08\x12\x1c\n\x18MODEL_STATE_INACCESSIBLE\x10\t\x12\x17\n\x13MODEL_STATE_INVALID\x10\nBM\n\x1a\x63om.triton.management.grpcZ\x16triton.management.grpc\xaa\x02\x16Triton.Management.Grpcb\x06proto3')

_MODELSTATE = DESCRIPTOR.enum_types_by_name['ModelState']
ModelState = enum_type_wrapper.EnumTypeWrapper(_MODELSTATE)
MODEL_STATE_UNKNOWN = 0
MODEL_STATE_PENDING = 1
MODEL_STATE_FETCHING = 2
MODEL_STATE_CACHED = 3
MODEL_STATE_LOADING = 4
MODEL_STATE_READY = 5
MODEL_STATE_UNLOADING = 6
MODEL_STATE_REMOVED = 7
MODEL_STATE_UNAVAILABLE = 8
MODEL_STATE_INACCESSIBLE = 9
MODEL_STATE_INVALID = 10


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.triton.management.grpcZ\026triton.management.grpc\252\002\026Triton.Management.Grpc'
  _MODELSTATE._serialized_start=47
  _MODELSTATE._serialized_end=343
# @@protoc_insertion_point(module_scope)
