# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tms_python_client.proto.Tms import allowlist_pb2 as proto_dot_Tms_dot_allowlist__pb2


class TritonAllowlistStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
                '/triton.management.server.TritonAllowlist/Append',
                request_serializer=proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistAppendRequest.SerializeToString,
                response_deserializer=proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistAppendResponse.FromString,
                )
        self.List = channel.unary_stream(
                '/triton.management.server.TritonAllowlist/List',
                request_serializer=proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistListRequest.SerializeToString,
                response_deserializer=proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistListResponse.FromString,
                )
        self.Remove = channel.unary_unary(
                '/triton.management.server.TritonAllowlist/Remove',
                request_serializer=proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistRemoveRequest.SerializeToString,
                response_deserializer=proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistRemoveResponse.FromString,
                )


class TritonAllowlistServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Append(self, request, context):
        """Append one or more values to the list of allowed to deploy container images.
        When no images are provided an error will be returned.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Lists all container images contained in the list of allowed to deploy container images
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Removes one or more values from the list of allowed to deploy container images.
        When no images are provided an error will be returned.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TritonAllowlistServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistAppendRequest.FromString,
                    response_serializer=proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistAppendResponse.SerializeToString,
            ),
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistListRequest.FromString,
                    response_serializer=proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistListResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistRemoveRequest.FromString,
                    response_serializer=proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistRemoveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'triton.management.server.TritonAllowlist', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TritonAllowlist(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/triton.management.server.TritonAllowlist/Append',
            proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistAppendRequest.SerializeToString,
            proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistAppendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/triton.management.server.TritonAllowlist/List',
            proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistListRequest.SerializeToString,
            proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/triton.management.server.TritonAllowlist/Remove',
            proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistRemoveRequest.SerializeToString,
            proto_dot_Tms_dot_allowlist__pb2.TritonAllowlistRemoveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
