# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Tms/lease-event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tms_python_client.proto import common_pb2 as proto_dot_common__pb2
try:
  proto_dot_error__code__pb2 = proto_dot_common__pb2.proto_dot_error__code__pb2
except AttributeError:
  proto_dot_error__code__pb2 = proto_dot_common__pb2.proto.error_code_pb2

from tms_python_client.proto.common_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/Tms/lease-event.proto\x12\x18triton.management.server\x1a\x12proto/common.proto\"\x96\x01\n\nLeaseEvent\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12/\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1c.triton.management.Timestamp\x12\x36\n\x04type\x18\x04 \x01(\x0e\x32(.triton.management.server.LeaseEventType*\xa3\x01\n\x0eLeaseEventType\x12\x1c\n\x18LEASE_EVENT_TYPE_UNKNOWN\x10\x00\x12\x1b\n\x17LEASE_EVENT_TYPE_STATUS\x10\x01\x12\x1c\n\x18LEASE_EVENT_TYPE_WARNING\x10\x02\x12\x1a\n\x16LEASE_EVENT_TYPE_ERROR\x10\x03\x12\x1c\n\x18LEASE_EVENT_TYPE_FAILURE\x10\x04\x42M\n\x1a\x63om.triton.management.grpcZ\x16triton.management.grpc\xaa\x02\x16Triton.Management.GrpcP\x00\x62\x06proto3')

_LEASEEVENTTYPE = DESCRIPTOR.enum_types_by_name['LeaseEventType']
LeaseEventType = enum_type_wrapper.EnumTypeWrapper(_LEASEEVENTTYPE)
LEASE_EVENT_TYPE_UNKNOWN = 0
LEASE_EVENT_TYPE_STATUS = 1
LEASE_EVENT_TYPE_WARNING = 2
LEASE_EVENT_TYPE_ERROR = 3
LEASE_EVENT_TYPE_FAILURE = 4


_LEASEEVENT = DESCRIPTOR.message_types_by_name['LeaseEvent']
LeaseEvent = _reflection.GeneratedProtocolMessageType('LeaseEvent', (_message.Message,), {
  'DESCRIPTOR' : _LEASEEVENT,
  '__module__' : 'proto.Tms.lease_event_pb2'
  # @@protoc_insertion_point(class_scope:triton.management.server.LeaseEvent)
  })
_sym_db.RegisterMessage(LeaseEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.triton.management.grpcZ\026triton.management.grpc\252\002\026Triton.Management.Grpc'
  _LEASEEVENTTYPE._serialized_start=231
  _LEASEEVENTTYPE._serialized_end=394
  _LEASEEVENT._serialized_start=78
  _LEASEEVENT._serialized_end=228
# @@protoc_insertion_point(module_scope)
