name: remote ssh command
on:
  push:
    branches:
      - main
      - master

env:
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  S3_ACCESS_KEY: ${{secrets.JWT_SECRET}}
  S3_SECRET_KEY: ${{secrets.S3_SECRET_KEY}}
  MINIO_ROOTUSER: ${{secrets.MINIO_ROOTUSER}}
  MINIO_ROOTPASSWORD: ${{secrets.MINIO_ROOTPASSWORD}}
  KUBE_CONFIG: ${{secrets.KUBE_CONFIG}}
  KUBECONFIG: .kube/config

jobs:
  
  deploy:
    name: deploy
    # image: andrius/sshuttle
    # runs-on: ubuntu-latest
    runs-on: [self-hosted,denbi]
    container:
      # image: ubuntu:20.04
      # image: nektos/act-environments-ubuntu:18.04
      image: praqma/helmsman:v3.13.1-helm-v3.9.2
    steps:
    - run: sleep 5
    - uses: actions/checkout@master
    # - run: echo "${{secrets.KUBE_CONFIG}}" | base64 --decode >> "$KUBECONFIG"
    - run: mkdir -p .kube
    # - name: Setting up kubeconfig online
      # if: ${{ !env.ACT }}
      # run: echo "${{secrets.KUBE_CONFIG}}" >> .kube/config
    - name: Install deps
      # if: ${{ env.ACT }}
      run: apk add --update coreutils make
    # - name: Setting up kubeconfig - offline
    #   env:
    #     KUBE_CONFIG: ${{secrets.KUBE_CONFIG}}
    #   run: 'echo "$KUBE_CONFIG" | base64 --decode >> .kube/config'
    # - name: Checking secret
    #   run: echo $KUBE_CONFIG
    # - name: Get contexts
    #   run: kubectl config get-contexts   
    # - name: Test Kube connection
    #   run: kubectl get node  -o wide
    - name: test helm
      run: helm version
    - name: test helmsman 
      run: helmsman  -v
    - name: "make staging.dry"
      run: make staging.dry
  